version: '3'
services:
  todofront:
    build: todo-app/front-end
    restart: on-failure
    ports:
      - 3000:3000
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - trybe-network
  todoback:
    build: todo-app/back-end
    restart: on-failure
    ports:
      - 3001:3001
    networks:
      - trybe-network
  todotests:
    build: todo-app/tests
    depends_on:
      - todofront
      - todoback
    environment:
      - FRONT_HOST=todofront
    networks:
      - trybe-network
networks:
  trybe-network: